// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vumxmyaxgvjpviyeijoi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ1bXhteWF4Z3ZqcHZpeWVpam9pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NTY0MjAsImV4cCI6MjA3MjAzMjQyMH0.0-CSKFuW4gO_0zY1JJlPyfTpID2vnAP286sXmWgR0_0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});